"""MiniProxy connect helpers — shared by the dashboard, CLI, and TUI.

Everything needed to point an *external* browser or HTTP client (any OS,
any device, any network) at a running MiniProxy:

* :func:`external_ip` — best-effort local address without sending packets
  (a UDP "connect" is a pure routing-table lookup: no DNS, no traffic);
* :func:`candidate_hosts` — the hostnames the proxy is plausibly reachable
  on, best first. The dashboard passes the request's own Host header in
  first, which is exactly right for SSH tunnels and port-forwards;
* :func:`pac_body` — a Proxy Auto-Config script so browsers/OSes can
  configure themselves from a single URL instead of typing addresses;
* :func:`ca_cert_path` — where mitmproxy's CA lives (env-overridable).
"""
from __future__ import annotations

import os
import socket
from pathlib import Path
from urllib.parse import urlsplit

PAC_MIME = "application/x-ns-proxy-autoconfig"


def external_ip() -> str | None:
    """Best-effort external address without sending packets.

    ``socket.connect`` on a UDP socket only consults the routing table —
    nothing goes on the wire, so this works offline and never does DNS.
    Link-local addresses (169.254.x.x, fec0::/10, fe80::/10) are skipped:
    they are per-segment plumbing, unreachable from other devices.
    """
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(0.5)
        try:
            s.connect(("8.8.8.8", 80))
            ip = str(s.getsockname()[0])
            if ip.startswith("169.254."):
                return None  # link-local — not routable from anywhere else
            return ip
        finally:
            s.close()
    except OSError:
        return None


def candidate_hosts(
    request_host: str | None = None,
    *,
    include_loopback: bool = True,
) -> list[dict[str, str]]:
    """Hostnames the proxy is plausibly reachable on, best first.

    The request's own Host header wins — it is exactly right for SSH
    tunnels, port-forwards, and named hosts, where interface enumeration
    would only mislead. Loopback is last (it only works on this machine).
    """
    out: list[dict[str, str]] = []
    seen: set[str] = set()

    def add(host: str, label: str) -> None:
        host = (host or "").strip()
        if not host or host in seen or host in ("0.0.0.0", "::", "*", ""):
            return
        if not include_loopback and (
            host in ("localhost", "::1")
            or host.startswith("127.")
            or host.startswith("[::1]")
        ):
            return
        seen.add(host)
        out.append({"host": host, "label": label})

    if request_host:
        hdr = urlsplit(f"//{request_host}").hostname or ""
        add(hdr, "this dashboard's address")
    ext = external_ip()
    if ext:
        add(ext, "external interface (VPS / public IP)")
    try:
        lan = socket.gethostbyname(socket.gethostname())
        if not lan.startswith("169.254."):
            add(lan, "LAN address")
        else:  # keep the list useful even when only link-local exists
            add(lan, "LAN address (link-local — usually device-local only)")
    except OSError:
        pass
    if include_loopback:
        add("127.0.0.1", "same machine only")
    return out


def resolve_proxy_target(
    proxy_host: str | None,
    proxy_port: int | None,
    request_host: str | None = None,
    *,
    running_port: int | None = None,
    default_port: int = 8080,
) -> tuple[str, int]:
    """Resolve the proxy host:port to advertise.

    Precedence: explicit override → request host → first candidate →
    loopback; the port comes from the override, else the running proxy,
    else *default_port*.
    """
    host = (proxy_host or "").strip()
    if not host:
        cands = candidate_hosts(request_host)
        host = cands[0]["host"] if cands else "127.0.0.1"
    port = proxy_port or running_port or int(default_port)
    return host, int(port)


def pac_body(proxy_host: str, proxy_port: int) -> str:
    """Proxy Auto-Config script routing everything through MiniProxy."""
    proxy = f"{proxy_host}:{proxy_port}"
    return (
        "// MiniProxy PAC — auto-generated by the dashboard\n"
        f"// Routes all HTTP(S) traffic through MiniProxy at {proxy}\n"
        "function FindProxyForURL(url, host) {\n"
        "  if (shExpMatch(host, 'localhost') || host === '127.0.0.1' || "
        "host === '::1' || host === '[::1]') {\n"
        "    return 'DIRECT';\n"
        "  }\n"
        f"  return 'PROXY {proxy}; DIRECT';\n"
        "}\n"
    )


def ca_cert_path() -> Path:
    """mitmproxy's CA certificate path (``MINIPROXY_CA_CERT`` overrides)."""
    override = os.environ.get("MINIPROXY_CA_CERT")
    return Path(override) if override else Path.home() / ".mitmproxy" / "mitmproxy-ca-cert.pem"
